# Generated by Django 3.2.16 on 2023-01-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Surname')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('patronymic', models.CharField(blank=True, max_length=50, verbose_name='Patronymic')),
                ('education', models.TextField(verbose_name='Education')),
                ('experience', models.PositiveSmallIntegerField(default=0, verbose_name='Experience')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='trainers_images', verbose_name='Image')),
            ],
        ),
    ]
