# Generated by Django 3.2.16 on 2023-01-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_trainer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='image',
            field=models.ImageField(blank=True, default='/static/img/default-avatar.png', null=True, upload_to='trainers_images', verbose_name='Image'),
        ),
    ]
