# Generated by Django 3.2.16 on 2023-03-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_trainer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=100, verbose_name='Days')),
                ('time', models.TextField(max_length=1000, verbose_name='Time')),
            ],
        ),
    ]
