# Generated by Django 3.2.16 on 2023-06-01 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events_images', verbose_name='Image')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('event_place', models.CharField(max_length=255, verbose_name='Event Place')),
                ('description', models.TextField(max_length=10000, verbose_name='Description')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 6, 1, 16, 12, 21, 142525), verbose_name='Date And Time')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
